version: "3.9"

services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./source_data:/docker-entrypoint-initdb.d:ro
    networks:
      - geonetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - geonetwork
      
  superset:
    image: apache/superset:latest-dev
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SUPERSET_ADMIN_USERNAME=${SUPERSET_ADMIN_USERNAME}
      - SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
      - SUPERSET_ADMIN_EMAIL=${SUPERSET_ADMIN_EMAIL}
      - SUPERSET_ADMIN_FIRST_NAME=${SUPERSET_ADMIN_FIRST_NAME}
      - SUPERSET_ADMIN_LAST_NAME=${SUPERSET_ADMIN_LAST_NAME}
    ports:
      - "${SUPERSET_PORT}:8088"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - geonetwork
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username ${SUPERSET_ADMIN_USERNAME} --firstname ${SUPERSET_ADMIN_FIRST_NAME} --lastname ${SUPERSET_ADMIN_LAST_NAME} --email ${SUPERSET_ADMIN_EMAIL} --password ${SUPERSET_ADMIN_PASSWORD} &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"

volumes:
  postgres_data:

networks:
  geonetwork:
    driver: bridge
