# 
# File: /home/patrick/Documents/Projects/modern-data-architectures/handzon-pyspark/spark-node/Dockerfile
# Project: /home/patrick/Documents/Projects/modern-data-architectures/handzon-pyspark/spark-node
# Created Date: Tuesday, May 6th 2025, 6:40:51 pm
# Author: Patrick S. Kanmeugne
# -----
# Last Modified: Tue May 06 2025
# Modified By: Patrick S. Kanmeugne
# -----
# Copyright (c) 2025 AiConLab
# 
# -----
# HISTORY:
# Date      	By	Comments
# ----------	---	----------------------------------------------------------
# 

FROM bitnami/spark:3.4

USER root
RUN pip install \
    py4j==0.10.9.7 \
    ipython








